// ============================================================
// Payroll.jsx — Employee: view own payroll records
// API: GET /payroll/my?month=
// ============================================================

import { useEffect, useState } from "react";
import { getMyPayroll } from "../api/payrollApi";

// Format month YYYY-MM → "April 2026"
const fmtMonth = (m) => {
  const [y, mo] = m.split("-");
  return new Date(y, mo - 1).toLocaleDateString("en-US", { month: "long", year: "numeric" });
};

const fmt = (n) => `$${Number(n).toLocaleString()}`;

export default function EmployeePayroll() {
  const [records, setRecords]       = useState([]);
  const [loading, setLoading]       = useState(true);
  const [error, setError]           = useState("");
  const [monthFilter, setMonthFilter] = useState("");

  useEffect(() => {
    fetchPayroll();
  }, [monthFilter]);

  const fetchPayroll = async () => {
    setLoading(true);
    setError("");
    console.log("[PAYROLL] Fetching payroll...");
    try {
      const data = await getMyPayroll(monthFilter);
      setRecords(data);
      console.log("[PAYROLL] Records loaded:", data.length);
    } catch (err) {
      console.error("[PAYROLL ERROR] Fetch failed:", err.message);
      setError("Failed to load payroll data.");
    } finally {
      setLoading(false);
    }
  };

  // Skeleton
  if (loading) {
    return (
      <div>
        <div className="mb-6 h-8 w-32 bg-slate-200 dark:bg-slate-700 rounded animate-pulse" />
        <div className="space-y-3">
          {[...Array(3)].map((_, i) => (
            <div key={i} className="h-28 rounded-xl bg-slate-200 dark:bg-slate-800 animate-pulse" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Payroll</h1>
          <p className="text-slate-500 dark:text-slate-400 text-sm mt-1">Your salary records</p>
        </div>
        <input type="month" value={monthFilter}
          onChange={(e) => setMonthFilter(e.target.value)}
          className="px-3 py-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
        />
      </div>

      {/* Error */}
      {error && (
        <div className="mb-5 flex items-center gap-2 p-4 rounded-xl bg-red-50 dark:bg-red-500/10 border border-red-200 dark:border-red-500/30 text-red-600 dark:text-red-400 text-sm">
          <svg className="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          {error}
        </div>
      )}

      {/* Empty */}
      {!error && records.length === 0 && (
        <div className="flex flex-col items-center justify-center py-16 text-center bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl">
          <div className="text-5xl mb-4">💰</div>
          <p className="text-slate-700 dark:text-slate-300 font-semibold text-lg">No payroll records available yet.</p>
          <p className="text-slate-400 text-sm mt-1">Your payroll will appear here once generated.</p>
        </div>
      )}

      {/* Payroll cards */}
      <div className="space-y-4">
        {records.map((r) => (
          <div key={r._id} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 md:p-6">
            {/* Month header */}
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-base font-bold text-slate-900 dark:text-white">{fmtMonth(r.month)}</h3>
              <span className="text-xs text-slate-400">
                Generated by {r.generatedBy?.name || "Admin"}
              </span>
            </div>

            {/* Salary breakdown grid */}
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/50">
                <p className="text-xs text-slate-400 mb-1">Base Salary</p>
                <p className="text-lg font-bold text-slate-900 dark:text-white">{fmt(r.baseSalary)}</p>
              </div>
              <div className="p-3 rounded-xl bg-amber-50 dark:bg-amber-500/10">
                <p className="text-xs text-amber-500 mb-1">Absent Days</p>
                <p className="text-lg font-bold text-amber-600 dark:text-amber-400">{r.absentDays}</p>
              </div>
              <div className="p-3 rounded-xl bg-red-50 dark:bg-red-500/10">
                <p className="text-xs text-red-500 mb-1">Deduction</p>
                <p className="text-lg font-bold text-red-600 dark:text-red-400">-{fmt(r.deduction)}</p>
              </div>
              <div className="p-3 rounded-xl bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/20">
                <p className="text-xs text-emerald-500 mb-1">Net Salary</p>
                <p className="text-xl font-bold text-emerald-600 dark:text-emerald-400">{fmt(r.netSalary)}</p>
              </div>
            </div>

            {/* Deduction note */}
            {r.absentDays > 0 && (
              <p className="text-xs text-slate-400 mt-3">
                Deduction: {r.absentDays} absent day{r.absentDays > 1 ? "s" : ""} × $500 = {fmt(r.deduction)}
              </p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
